DROP TABLE IF EXISTS cuenta;
DROP TABLE IF EXISTS usuario;

CREATE TABLE cuenta (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tipo VARCHAR(50) NOT NULL,
  fecha_apertura DATE NOT NULL,
  balance NUMERIC(20, 2),
  ownerId BIGINT NOT NULL
);

CREATE TABLE usuario (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  mail VARCHAR(100) NOT NULL
);